name: tfg_flutter_laura
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.3
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  intl: 0.19.0
  open_file: ^3.3.2  # Para el manual usuario pero al final nada
  syncfusion_flutter_pdfviewer: ^24.1.41 # apuntar biblio igualmente
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  windows: true
  image_path: "assets/icon/logo.png" # se ha añdido logo

flutter:

  uses-material-design: true
  assets:
    - assets/img/
    - assets/docs/Manual_usuario_Tasknelia.pdf
    - assets/icon/


